packages:
  - packages/*
  - e2e
  - website
  - '!packages/http-client-csharp/**'
  - '!packages/http-client-java/**'
  - '!packages/http-client-python/**'

overrides:
  cross-spawn@>=7.0.0 <7.0.5: ^7.0.5
  "@alloy-js/core": "^0.21.0-dev.10"
  "@alloy-js/python": "^0.2.0-dev.4"
  rollup: 4.49.0

registry: https://registry.npmjs.org/
