name: Pull Request Checks (Pinterest)
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 ## Needed for Changesets to find `main` branch

      - uses: ./.github/actions/setup

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run

      - name: Test
        run: pnpm test

